### ISSUE TITLE
OpenCore (OCCPU) detects wrong CPU topology

### ISSUE THREAD

**Issue by TannerCS** [Qonfused/OSX-Hyper-V#24] opened 2024-11-02 20:03 UTC
CPU: Ryzen 5 5900X (12c 24t)
Mobo: asus strix B350f
OS: Windows 10 Pro 22H2 (19045.5073)
macOS: Latest Sequoia

```
...
13:688 00:002 OC: Prelinked injection AMDRyzenCPUPowerManagement.kext (AMDRyzenCPUPowerManagement.kext) - Success
13:690 00:001 OC: Prelinked injection AMDRyzenCPUPowerManagement.kext v0.7.2
13:691 00:001 OC: Prelink size 66420736 kext offset 65081344 reserved 1339392
13:693 00:001 OCAK: KC TEXT is 65536 bytes with 61800 Mach-O headers need 472
13:707 00:014 OCAK: Patching invalid size 2FFE with 236E000 for com.apple.driver.AppleSMBIOS
13:709 00:001 OCAK: 64-bit CustomSmbiosGuid replace count - 1
13:711 00:001 OCAK: [OK] SMBIOS Patch success
13:713 00:001 OCAK: Patching invalid size 77FF1 with 2B2C000 for com.apple.driver.AppleACPIPlatform
13:714 00:001 OCAK: 64-bit CustomSmbiosGuid replace count - 1
13:716 00:001 OCAK: [OK] SMBIOS Patch success
13:719 00:003 OCAK: Failed to pk find com.apple.driver.AppleIntelCPUPowerManagement - Not Found
13:721 00:001 OCAK: [OK] Skipping dummy AppleIntelCPUPowerManagement patch on 240100
13:723 00:001 OCAK: 64-bit CaseySJ | probeBusGated | Disable 10 bit tags | 12.0+ replace count - 1
13:725 00:001 OC: Prelinked patcher result 17 for com.apple.iokit.IOPCIFamily (CaseySJ | probeBusGated | Disable 10 bit tags | 12.0+) - Success
13:749 00:024 OC: Prelinked status - Success
13:758 00:008 AAPL: #[EB.LD.LKFS|-?] Ok(0)
13:760 00:001 AAPL: #[EB.LD.LKC|-?] Ok(0)
13:761 00:001 AAPL: #[EB|BST:REV1]
13:763 00:001 AAPL: #[EB.CSR.F|!] Err(0xE) <- RT.GV csr-active-config 7C436110-AB2A-4BBB-A880-FE41995C9F82
13:765 00:001 AAPL: #[EB|CSR:OUT] 0x00000000
13:768 00:003 AAPL: #[EB.BST.FBS|+]
13:770 00:001 AAPL: #[EB.BST.FBS|ADSZ] 0
13:771 00:001 AAPL: #[EB.BST.FBS|KSSZ] 0
13:773 00:001 AAPL: #[EB|SB:SBGMFNS] x86legacyap.im4m
13:775 00:001 AAPL: #[EB|RH:PF] usr\standalone\OS.dmg.root_hash
13:777 00:001 AAPL: #[EB|RH:MF] <"usr\\standalone\\OS.dmg.root_hash.x86legacyap.im4m">
13:778 00:001 AAPL: #[EB.LD.LF|IN] 0 1 <"usr\\standalone\\OS.dmg.root_hash"> <"0">
13:784 00:005 AAPL: #[EB.LD.OFS|OPEN!] Err(0xE) <"usr\\standalone\\OS.dmg.root_hash">
13:785 00:001 AAPL: #[EB.RH.LRH|P!] Err(0xE) <- EB.LD.LF
13:787 00:001 AAPL: #[EB.BST.FBS|!] Err(0xE) <- EB.RH.LRH
13:789 00:001 OCSMC: SmcReadValue Key 4D535463 Size 1
13:791 00:002 OCSMC: SmcReadValue Key 4D534163 Size 2
13:793 00:002 AAPL: #[EB|LOG:DT] 2024-11-02T14:52:54
13:795 00:002 AAPL: #[EB|LOG:EXITBS:START] 2024-11-02T14:52:54
```

Been trying to tackle this issue for the past few days with no luck. Hoping someone can tell me if I'm missing something. I've tried enabling/disabling and installing/uninstalling many different kexts like voodoo, whatevergreen, etc. with no success. I've looked through #5 and everyone's discussions about it and double checked everything. I've went through dortania's troubleshooting page and experiemented with the [[EB|#LOG:EXITBS:START]](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-eb-log-exitbs-start). OpenVariableRuntime driver loads up the apple logo, but other than that, it's still the same error.

I've had macos running bare metal with this hardware before, so I know it's compatible. I just can't get it to boot through hypervisor

[EFI.zip](https://github.com/user-attachments/files/17608199/EFI.zip)
[opencore-2024-11-02-145241.txt](https://github.com/user-attachments/files/17608202/opencore-2024-11-02-145241.txt)

**Comment by Qonfused** [comment] 2024-11-02 20:27
You shouldn't need any additional kexts for AMD (including `AMDRyzenCPUPowerManagement`) or the `OpenVariableRuntimeDxe` driver. They kernel patches you have and enabling **Kernel > Emulate > DummyPowerManagement** should be all you need for the 5900X.

I did notice that you're missing the MinKernel/MaxKernel values for `MacHyperVSupport` and `MacHyperVSupportMonterey`:

![image](https://github.com/user-attachments/assets/f4c87fbb-3f31-400f-8a25-7663e92234fa)

https://github.com/Qonfused/OSX-Hyper-V/blob/f0e99b5695b1bd6ae571e79c1bccaa4d623fabfb/src/build.yml#L21-L30

The 'MacHyperVSupportMonterey' kext is for Monterey and above, so you'll want to leave that one enabled when booting Sequoia. I imagine this may have happened after swapping out kexts so it's possible this may have confounded your earlier testing.

For the minute I'd make sure MacHyperVSupportMonterey is enabled and OpenVariableRuntimeDxe is disabled.

**Comment by TannerCS** [comment] 2024-11-03 00:00
Still getting the same error, but no boot loop anymore. It just hangs when getting to the point of booting into recovery.

<video src='https://i.tnrs.world/9OcQJR.mp4'></video>

[opencore-2024-11-02-184609.txt](https://github.com/user-attachments/files/17608679/opencore-2024-11-02-184609.txt)

**Comment by Qonfused** [comment] 2024-11-03 01:54
Still looking into why this is happening since MacHyperVSupportMonterey is loading correctly. From what I can tell it's getting stuck in PCI allocation just before `HID: Legacy shim 2`, which is much earlier in the boot process than in #13.

I don't believe OpenVariableRuntimeDxe did anything previously (since it and OpenRuntime require 'LoadEarly' enabled and for OpenRuntime to be loaded after). It may be worth clearing NVRAM inside the VM (which is emulated in Hyper-V and persisted in the VM's configuration file).

Alternatively you can try booting into Sonoma or Ventura with the same setup to see if the same issue persists.

**Comment by TannerCS** [comment] 2024-11-03 04:40
[Same thing after resetting NVRAM](https://github.com/user-attachments/files/17609367/opencore-2024-11-02-232935.txt)

[Also same thing after trying Sonoma](https://github.com/user-attachments/files/17609389/opencore-2024-11-02-233423.txt)

[And as a sanity check, I even tried with Ventura](https://github.com/user-attachments/files/17609395/opencore-2024-11-02-233817.txt)

**Comment by Qonfused** [comment] 2024-11-03 21:37
Taking another look now. Being stuck during PCI allocation is suggestive that there is something wrong with the AMD kernel patches, but I wasn't sure if something was persisting from earlier boot attempts.

Something to note is that you'll need to specify a custom core count for the 5900X (it seems you patched for 8 cores instead of 12). You'll need to change the second bit in the `Replace` field from `08` to `0C` for first 4 kernel patches:

|   macOS Version      | `Replace` Value |
|----------------------|-----------------|
| 10.13.x, 10.14.x     | `B80C0000 0000` |
| 10.15.x, 11.x        | `BA0C0000 0000` |
| 12.x, 13.0 to 13.2.1 | `BA0C0000 0090` |
| 13.3+                | `BA0C0000 00`   |

^ These are the correct values for the `Replace` field for the 4 `cpuid_cores_per_package` patches.

**Comment by TannerCS** [comment] 2024-11-03 21:52
I have it set to 8 cores because that's what the logs present and I've had issues trying to set it to 12 cores. 
`00:050 00:002 OCCPU: Pkg 1 Cores 8 Threads 16`

However, I have the hypervisor set to use 12 cores, so I'm not sure what the deal is there.

[Setting core count to 12 instead of 8](https://github.com/user-attachments/files/17612215/opencore-2024-11-03-154855.txt)
[config.plist](https://github.com/user-attachments/files/17612218/config.zip)

**Comment by Qonfused** [comment] 2024-11-03 22:31
Interesting. I assume task manager or CPU-Z detects all 12 cores enabled? If there are any issues detecting cores outside of Hyper-V I'd try reinstalling the chipset driver for your motherboard.

Assuming that cores are disabled (and not simply a detection issue), if there are BIOS settings for the CPU I'd check if there's a way to enable/disable CPU cores.

Normally if there were any disabled cores it'd disable 6 cores or half of the processor (since the 5900X has a 6+6 CCX layout). It's also possible that 4 cores are disabled from 'Game Mode' in Ryzen Master but that should disable 6 cores instead of 4.

**Comment by TannerCS** [comment] 2024-11-03 23:03
Yep. Task manager/cpu-z shows as 12 cores and 24 threads. I haven't touched anything with unparking cores or anything like that if that's what you're talking about. This is a fresh install of Windows. I also don't have that setting enabled in the bios that allows you to disable cores and threads for a higher core clock. Forgot what that one was called

**Comment by Qonfused** [comment] 2024-11-04 00:21
Seems like the wrong thread count is extracted from the CPUID instruction (from OpenCore's OcCpuLib):
https://github.com/acidanthera/OpenCorePkg/blob/6fb63d4/Library/OcCpuLib/OcCpuLib.c#L666-L672

```cpp
666 |  //
667 |  // Get core and thread count from CPUID
668 |  //
669 |  if (Cpu->MaxExtId >= 0x80000008) {
670 |    AsmCpuid (0x80000008, NULL, NULL, &CpuidEcx, NULL);
671 |    Cpu->ThreadCount = (UINT16)(BitFieldRead32 (CpuidEcx, 0, 7) + 1);
672 |  }
```

This throws off the core count # as it's calculated by dividing the thread count by the number of threads per core:
https://github.com/acidanthera/OpenCorePkg/blob/6fb63d4/Library/OcCpuLib/OcCpuLib.c#L737-L748
```cpp
692 |  switch (Cpu->ExtFamily) {
...
722 |      case AMD_CPU_EXT_FAMILY_17H:
723 |      case AMD_CPU_EXT_FAMILY_19H:
...
737 |        //
738 |        // Get core count from CPUID
739 |        //
740 |        if (Cpu->MaxExtId >= 0x8000001E) {
741 |          AsmCpuid (0x8000001E, NULL, &CpuidEbx, NULL, NULL);
742 |          Cpu->CoreCount = (UINT16)DivU64x32 (
743 |                                     Cpu->ThreadCount,
744 |                                     (BitFieldRead32 (CpuidEbx, 8, 15) + 1)
745 |                                     );
746 |        }
747 |
748 |        break;
```

If you can, I'd try booting into a DEBUG version of OpenCore on bare metal to output a log file (don't try and select any boot entries, just get to the OpenCore picker and shut off the machine). You can create a new FAT32 partition and re-use the same EFI folder you have for Hyper-V.

Ideally the log should report the correct core count, which would suggest that it is Hyper-V related (somehow it's intercepting the `0x8000001E` CPUID instruction which should only ever return CPU topology information).

**Comment by TannerCS** [comment] 2024-11-04 01:08
As expected lol. `01:168 00:037 OCCPU: Pkg 1 Cores 12 Threads 24`
[opencore-2024-11-03-190603.txt](https://github.com/user-attachments/files/17612829/opencore-2024-11-03-190603.txt)

**Comment by Qonfused** [comment] 2024-11-04 01:12
CPU frequencies are also incorrectly reported in the log w/ Hyper-V. Will take another look in a minute.

**Comment by TannerCS** [comment] 2024-11-04 01:14
Here's my ryzen master just for the fun of it. Didn't even know it was installed. Must have come with the graphics drivers

![ryzen](https://i.tnrs.world/ixY1Nj.png)

**Comment by eAtmApp** [comment] 2024-11-07 06:40
May I ask if you have resolved it? I tried to install it on my X570 and 3950X last year as well, and encountered the same error. Both ESXi and Hyper-V failed at that time, but I was able to install and use it normally with a physical machine and PVE.

If resolved, please share the solution. Thank you very much!

**Comment by Qonfused** [comment] 2024-11-07 12:24
@eAtmApp Would you be able to try again using the [v0.2.0](https://github.com/Qonfused/OSX-Hyper-V/releases/tag/0.2.0) release (or rebuild the project locally)? There have been some fixes over the last year that may impact your issue.

**Comment by eAtmApp** [comment] 2024-11-07 14:35
> @eAtmApp Would you be able to try again using the [v0.2.0](https://github.com/Qonfused/OSX-Hyper-V/releases/tag/0.2.0) release (or rebuild the project locally)? There have been some fixes over the last year that may impact your issue.

@Qonfused After using the EFI -> config.plist from the previous reply and replacing it with the v0.2.0 release, it indeed doesn't restart, but when booting the installer later, there are still other errors that cause it to hang. It seems to be really unfriendly towards AMD CPUs.

**Comment by eAtmApp** [comment] 2024-11-08 03:21
@Qonfused 
I used the EFI files from [[#4 (comment)]](https://github.com/Qonfused/OSX-Hyper-V/issues/24#issuecomment-2453230126) and replaced them with the version from [v0.2.0](https://github.com/Qonfused/OSX-Hyper-V/releases/tag/0.2.0), modifying the cpuid_cores_per_package core count.

It seems that the situation is the same whether or not the version is replaced with [v0.2.0](https://github.com/Qonfused/OSX-Hyper-V/releases/tag/0.2.0).

[opencore-2024-11-08-110600.txt](https://github.com/user-attachments/files/17672134/opencore-2024-11-08-110600.txt)

[EFI.zip](https://github.com/user-attachments/files/17672144/EFI.zip)

![image](https://github.com/user-attachments/assets/94eb555e-e90a-4b32-b4a5-72c4a5549fde)

**Comment by eAtmApp** [comment] 2024-11-08 03:22
Last year, I tried using macOS 13, and this time I'm using macOS 14 and 15.

**Comment by Qonfused** [comment] 2024-11-08 04:10
The core (vCPU) count in the VM is set by the number assigned to it, which essentially schedules a virtual processor to run when a physical processor is free. You can exceed the number of physical cores (up to 64 or 128 I believe), but at maximum only 16 cores will actually be used at a time.

I had assumed the number assigned was identical to the number of physical cores but I definitely should have verified this in case this was a very trivial problem.

**Comment by eAtmApp** [comment] 2024-11-08 06:08
I used this config.plist from https://github.com/Qonfused/OSX-Hyper-V/issues/13#issuecomment-2409096933. After adding the _cpu_syscall_init patch, I was able to successfully enter the installation program interface.

[OC_EFI_Ryzen3950X(16C_32T).zip](https://github.com/user-attachments/files/17674117/OC_EFI_Ryzen3950X.16C_32T.zip)

![image](https://github.com/user-attachments/assets/f0674df9-eb59-40b0-8acd-c69b9e870843)

**Comment by Qonfused** [comment] 2024-11-08 06:30
Strange, I don't see any functional differences between the two. There's no need for WhateverGreen w/ MacHyperVSupport but that's the only real change made outside of the SMBIOS.

**Comment by eAtmApp** [comment] 2024-11-08 17:12
I just tested it, and the WhateverGreen.kext can be disabled.
Setting "PI"->"Generic"->"SystemProductName" to iMac11, iMac19, or iMac20 can allow booting.
iMacPro and MacPro7 cannot boot.
I didn't try the others.

**Comment by Qonfused** [comment] 2024-11-21 02:36
> I just tested it, and the WhateverGreen.kext can be disabled. Setting "PI"->"Generic"->"SystemProductName" to iMac11, iMac19, or iMac20 can allow booting. iMacPro and MacPro7 cannot boot. I didn't try the others.

I'd note that both the `iMacPro1,1` and `MacPro7,1` SMBIOSes (Skylake-W and CascadeLake-W) require the [AppleMCEReporterDisabler](https://github.com/acidanthera/bugtracker/files/3703498/AppleMCEReporterDisabler.kext.zip) kext for macOS Monterey 12.3+.

**Comment by Qonfused** [comment] 2024-11-21 02:42
I still haven't been able to determine why https://github.com/Qonfused/OSX-Hyper-V/issues/24#issuecomment-2453589567 happens on a fresh Windows installation; so far I've been unable to reproduce it on 23H2 and 24H4 versions of Windows 10 and 11 (both Pro and Server builds). In my testing I've ran Windows with a stock installation and ran VM configuration via `create-virtual-machine.ps1`.

There doesn't seem to be any obvious hardware or configuration issues in the original issue as far as I can tell, though https://github.com/Qonfused/OSX-Hyper-V/issues/24#issuecomment-2463859043 suggests a workaround for the same issue assuming it is a misconfiguration issue w/ the SMBIOS (also see the above https://github.com/Qonfused/OSX-Hyper-V/issues/24#issuecomment-2489944091).

Though this EFI and config.plist from https://github.com/Qonfused/OSX-Hyper-V/issues/13#issuecomment-2409096933 is the same as in v0.2.0 (following AMD-specific instructions in the README). It doesn't seem to affect other AMD systems consistently (nor does it affect my 3950X system), so there doesn't seem to be anything addressable in the current build.

**Comment by TannerCS** [comment] 2024-11-21 02:43
> May I ask if you have resolved it? I tried to install it on my X570 and 3950X last year as well, and encountered the same error. Both ESXi and Hyper-V failed at that time, but I was able to install and use it normally with a physical machine and PVE.
> 
> If resolved, please share the solution. Thank you very much!

Sorry for the much late reply. No, I did not end up fixing it. Instead, I ended up doing what I was originally going to do and bought a new GPU for one of my workstations that's on Linux and put macOS VM on that so I can have a seamless linux/macos workstation with bare metal performance.

**Closed by Qonfused** 2024-11-21 02:42 UTC
Labels: type:bug, status:investigating, workaround available

**Comment by eAtmApp** [comment] 2024-11-21 13:38
> I'd note that both the `iMacPro1,1` 和 `MacPro7,1` SMBIOSes (Skylake-W 和 CascadeLake-W) require the [AppleMCEReporterDisabler](https://github.com/acidanthera/bugtracker/files/3703498/AppleMCEReporterDisabler.kext.zip) kext for macOS Monterey 12.3+.

After enabling the AppleMCEReporterDisabler patch, I can use information from iMacPro1,1 and MacPro7,1, but macOS 15 Sequoia still cannot log into Apple ID, while macOS 14 can log in normally. Do you know what might be causing this issue? Additionally, I am using Windows Server 2025; could this be related?



![image](https://github.com/user-attachments/assets/798f1c15-cb17-46cb-9b8f-da47163c37c8)

**Comment by eAtmApp** [comment] 2024-11-21 13:45
> Sorry for the much late reply. No, I did not end up fixing it. Instead, I ended up doing what I was originally going to do 和 bought a new GPU for one of my workstations that's on Linux 和 put macOS VM on that so I can have a seamless linux/macos workstation with bare metal performance.

Oh, okay, I've installed it successfully, but there are still other issues.

**Comment by Qonfused** [comment] 2024-11-21 14:52
> After enabling the AppleMCEReporterDisabler patch, I can use information from iMacPro1,1 and MacPro7,1, but macOS 15 Sequoia still cannot log into Apple ID, while macOS 14 can log in normally. Do you know what might be causing this issue? Additionally, I am using Windows Server 2025; could this be related?

This is likely a side-effect of the VMMApple iCloud additions in Sequoia. You can use the [VMHide](<https://github.com/Carnations-Botanica/VMHide>) kext to fix this (I'll update the build later to include this for Sequoia).

**Comment by Qonfused** [comment] 2025-01-23 19:37
Updated documentation with a workaround in 857ee75682a19ca5cf7664783bacfd907d42f741; no direct fix for incorrect CPUID + topology info.

The number of cores patched w/ the `cpuid_cores_per_package` patches should match the number of cores (vCPUs) assigned to the VM, albeit this number can exceed the number of physical cores on the system.
